# Whether this reporter will be used to report a failed verification (default = true)
aureum.VSCodeDiffReporter.enabled = false

# Whether this reporter will be used to report a failed verification (default = true)
aureum.IntelliJDiffReporter.enabled = true

# Whether this reporter will be used to report a failed verification (default = true)
aureum.SimpleDiffReporter.enabled = true

# The maximum amount of diff lines shown before printing "x more lines differ" (default = 10)
aureum.SimpleDiffReporter.maxDiffs = 10

